#ifndef _GAME_CONTROLLER_H
#define _GAME_CONTROLLER_H

#include "../game/game.h"

typedef enum GameState {
	GAMESTATE_MENU,
	GAMESTATE_SETTINGS,
	GAMESTATE_LOAD,
	GAMESTATE_PLAYING,
	GAMESTATE_GAMEOVER,
	GAMESTATE_QUIT
} GameState;

#endif
