#ifndef _GAME_STATES_H
#define _GAME_STATES_H

typedef enum GameState {
	GAMESTATE_MENU,
	GAMESTATE_SETTINGS,
	GAMESTATE_LOAD,
	GAMESTATE_PLAYING,
	GAMESTATE_GAMEOVER,
	GAMESTATE_QUIT,
	GAMESTATE_SAVE,
	GAMESTATE_DELETE
} GameState;

#endif
